version: '3'

services:
  app:
    build: .
    volumes:
      - ..:/home/workspace
    ports:
      - '8080:80'
    depends_on:
      - db

  db:
    image: mariadb:10
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: realsecret
      MYSQL_DATABASE: sitedb
      MYSQL_USER: siteuser
      MYSQL_PASSWORD: secretpassword
    ports:
      - '8081:3306'

  adminer:
    image: adminer
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: nette
    ports:
      - 8082:8080

volumes:
  db-data:
